"""Seed the Trust Standard Library with 14+ rich standards."""
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from app.models.trust_standard_library import TrustStandardLibrary


STANDARDS = [
    # ── Online Presence ──
    {
        "standard_id": "https_v1",
        "name": "HTTPS Enabled",
        "slug": "https",
        "category": "online_presence",
        "subcategory": "security",
        "importance": "critical",
        "weight": 8,
        "max_points": 10,
        "scoring_logic": "Check if website URL scheme is HTTPS. Full points if HTTPS, zero otherwise.",
        "detection_type": "http_header",
        "detection_pattern": "response.url.scheme == 'https'",
        "detection_notes": "Uses httpx to fetch the URL and check the final response scheme after redirects.",
        "fallback_detection": "Check for HSTS header or redirect from HTTP to HTTPS",
        "evidence_required": "Screenshot showing padlock icon in browser address bar, or HTTP response headers showing HTTPS.",
        "evidence_type": "screenshot",
        "verification_method": "Visit URL in browser and confirm HTTPS in address bar. Check SSL certificate validity.",
        "recommendation_action": "Enable HTTPS on your website",
        "recommendation_detail": "Install an SSL/TLS certificate from a trusted provider (Let's Encrypt, Cloudflare, or your hosting provider). Configure automatic HTTP-to-HTTPS redirects.",
        "effort": "medium",
        "estimated_time": "1-2 hours",
        "expected_impact": "+10 points (critical for AI trust signals)",
        "prompt_reference": "improvement_recommendations",
        "ai_context_hint": "HTTPS is a fundamental trust signal for both users and AI systems like ChatGPT and Google AI.",
        "methodology_reference": "SSL/TLS best practices guide (internal doc)",
        "version": "1.0",
        "sort_order": 1,
    },
    {
        "standard_id": "business_categories_v1",
        "name": "Google Business Categories",
        "slug": "categories",
        "category": "online_presence",
        "subcategory": "discoverability",
        "importance": "high",
        "weight": 6,
        "max_points": 10,
        "scoring_logic": "Check if Google Business profile has primary and secondary categories set. 5 points per category up to 10.",
        "detection_type": "api_call",
        "detection_pattern": "google_places_details.categories",
        "detection_notes": "Requires Google Places Details API call. Falls back to mock data in development.",
        "fallback_detection": "Manual review of Google Business profile screenshots",
        "evidence_required": "Screenshot of Google Business profile showing category selection.",
        "evidence_type": "screenshot",
        "verification_method": "Log into Google Business Profile and verify categories are set correctly.",
        "recommendation_action": "Set primary and secondary business categories",
        "recommendation_detail": "Log into Google Business Profile. Navigate to 'Info' section. Select the most accurate primary category and add relevant secondary categories.",
        "effort": "low",
        "estimated_time": "15 mins",
        "expected_impact": "+10 points (improves AI classification)",
        "prompt_reference": "google_business_improvements",
        "ai_context_hint": "Categories help AI systems correctly classify and recommend your business.",
        "methodology_reference": "Google Business Profile optimisation guide",
        "version": "1.0",
        "sort_order": 2,
    },
    {
        "standard_id": "business_description_v1",
        "name": "Business Description",
        "slug": "description",
        "category": "online_presence",
        "subcategory": "content",
        "importance": "high",
        "weight": 5,
        "max_points": 5,
        "scoring_logic": "Check if Google Business profile has a description. 5 points if present, 0 if empty.",
        "detection_type": "api_call",
        "detection_pattern": "google_places_details.description",
        "detection_notes": "Requires Google Places Details API. Description should be 200-750 characters.",
        "fallback_detection": "Manual check of Google Business profile",
        "evidence_required": "Screenshot of Google Business profile description section.",
        "evidence_type": "screenshot",
        "verification_method": "View Google Business profile and confirm description exists and is complete.",
        "recommendation_action": "Write a complete business description",
        "recommendation_detail": "Write a 200-750 character description that includes your key services, unique selling points, and target keywords.",
        "effort": "low",
        "estimated_time": "30 mins",
        "expected_impact": "+5 points (improves AI understanding)",
        "prompt_reference": "google_business_improvements",
        "ai_context_hint": "AI systems use your business description to understand what you do and who you serve.",
        "methodology_reference": "Google Business Profile optimisation guide",
        "version": "1.0",
        "sort_order": 3,
    },
    # ── Reputation ──
    {
        "standard_id": "google_rating_v1",
        "name": "Google Rating",
        "slug": "rating",
        "category": "reputation",
        "subcategory": "social_proof",
        "importance": "critical",
        "weight": 9,
        "max_points": 15,
        "scoring_logic": "Rating ≥ 4.5 = 15 points, ≥ 4.0 = 10 points, ≥ 3.5 = 5 points, < 3.5 = 0 points.",
        "detection_type": "api_call",
        "detection_pattern": "google_places_details.rating",
        "detection_notes": "Requires Google Places Details API call.",
        "fallback_detection": "Manual review of Google Business profile",
        "evidence_required": "Screenshot of Google reviews showing current rating.",
        "evidence_type": "screenshot",
        "verification_method": "Search business on Google Maps and verify displayed rating.",
        "recommendation_action": "Improve Google rating above 4.0",
        "recommendation_detail": "Implement a systematic review generation process. Ask every satisfied customer to leave a review. Respond to all existing reviews professionally.",
        "effort": "medium",
        "estimated_time": "Ongoing (4-8 weeks to see improvement)",
        "expected_impact": "+5 to +15 points (significant trust signal)",
        "prompt_reference": "google_business_improvements",
        "ai_context_hint": "Google Rating is one of the strongest trust signals for both users and AI recommendation systems.",
        "methodology_reference": "Review generation playbook (internal doc)",
        "version": "1.0",
        "sort_order": 4,
    },
    {
        "standard_id": "google_reviews_v1",
        "name": "Google Review Volume",
        "slug": "reviews",
        "category": "reputation",
        "subcategory": "social_proof",
        "importance": "high",
        "weight": 7,
        "max_points": 10,
        "scoring_logic": "≥ 50 reviews = 10 points, ≥ 20 = 7 points, ≥ 10 = 5 points, ≥ 1 = 2 points, 0 = 0 points.",
        "detection_type": "api_call",
        "detection_pattern": "google_places_details.reviews_count",
        "detection_notes": "Requires Google Places Details API.",
        "fallback_detection": "Count reviews manually on Google Maps",
        "evidence_required": "Screenshot of Google review count.",
        "evidence_type": "screenshot",
        "verification_method": "Search business on Google Maps and verify total review count.",
        "recommendation_action": "Increase review volume",
        "recommendation_detail": "Create a review request system: email templates, SMS reminders, in-person prompts. Aim for 50+ reviews.",
        "effort": "low",
        "estimated_time": "Ongoing (2-4 weeks for first 10 reviews)",
        "expected_impact": "+5 to +10 points (builds credibility)",
        "prompt_reference": "review_request_email",
        "ai_context_hint": "Review volume signals business activity and customer satisfaction to AI systems.",
        "methodology_reference": "Review generation playbook (internal doc)",
        "version": "1.0",
        "sort_order": 5,
    },
    {
        "standard_id": "website_testimonials_v1",
        "name": "Website Testimonials",
        "slug": "testimonials",
        "category": "reputation",
        "subcategory": "social_proof",
        "importance": "medium",
        "weight": 5,
        "max_points": 5,
        "scoring_logic": "Check if website contains testimonial or review sections. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"testimonial|review|what our clients say|trustpilot|google review",
        "detection_notes": "Searches page text and link text for testimonial-related keywords.",
        "fallback_detection": "Manual review of website pages",
        "evidence_required": "Screenshot of testimonials section on website.",
        "evidence_type": "screenshot",
        "verification_method": "Browse website and locate testimonial section.",
        "recommendation_action": "Add testimonials section to website",
        "recommendation_detail": "Create a dedicated testimonials page or section on your homepage. Include real client names, photos, and specific results where possible.",
        "effort": "medium",
        "estimated_time": "2-4 hours",
        "expected_impact": "+5 points (social proof for AI and visitors)",
        "prompt_reference": "homepage_rewrite",
        "ai_context_hint": "Testimonials provide social proof that AI systems recognise as trust signals.",
        "methodology_reference": "Website trust signal guide (internal doc)",
        "version": "1.0",
        "sort_order": 6,
    },
    # ── Engagement ──
    {
        "standard_id": "cta_v1",
        "name": "Call-to-Action",
        "slug": "cta",
        "category": "engagement",
        "subcategory": "conversion",
        "importance": "high",
        "weight": 6,
        "max_points": 5,
        "scoring_logic": "Check if website has visible CTAs. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"get started|book now|sign up|call now|buy now|contact us today|free quote|request a call",
        "detection_notes": "Searches for common CTA phrases in page text and link text.",
        "fallback_detection": "Manual review of key pages",
        "evidence_required": "Screenshot showing clear CTA buttons on homepage.",
        "evidence_type": "screenshot",
        "verification_method": "Visit homepage and key landing pages — confirm CTAs are visible above the fold.",
        "recommendation_action": "Add clear calls-to-action",
        "recommendation_detail": "Place prominent CTAs on your homepage, service pages, and contact page. Use action-oriented language like 'Book Your Free Consultation'.",
        "effort": "low",
        "estimated_time": "1-2 hours",
        "expected_impact": "+5 points (improves conversion readiness)",
        "prompt_reference": "homepage_rewrite",
        "ai_context_hint": "Clear CTAs signal business activity and conversion readiness to AI systems.",
        "methodology_reference": "Conversion optimisation guide (internal doc)",
        "version": "1.0",
        "sort_order": 7,
    },
    {
        "standard_id": "contact_page_v1",
        "name": "Contact Page",
        "slug": "contact_page",
        "category": "engagement",
        "subcategory": "accessibility",
        "importance": "high",
        "weight": 6,
        "max_points": 5,
        "scoring_logic": "Check if website has a dedicated contact page. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"contact|get in touch|reach us|contact us",
        "detection_notes": "Searches for contact-related keywords in page text and navigation links.",
        "fallback_detection": "Manual check of navigation menu",
        "evidence_required": "Screenshot of contact page showing phone, email, and address.",
        "evidence_type": "screenshot",
        "verification_method": "Navigate to contact page and verify all contact methods are present.",
        "recommendation_action": "Create a dedicated contact page",
        "recommendation_detail": "Build a contact page with phone number, email address, physical address, contact form, and business hours.",
        "effort": "low",
        "estimated_time": "1-2 hours",
        "expected_impact": "+5 points (essential for AI visibility)",
        "prompt_reference": "service_pages",
        "ai_context_hint": "A contact page is one of the first things AI systems look for when validating a business.",
        "methodology_reference": "Website trust signal guide (internal doc)",
        "version": "1.0",
        "sort_order": 8,
    },
    {
        "standard_id": "service_pages_v1",
        "name": "Service/Product Pages",
        "slug": "service_pages",
        "category": "engagement",
        "subcategory": "content",
        "importance": "high",
        "weight": 6,
        "max_points": 5,
        "scoring_logic": "Check if website has dedicated service or product pages. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"services|products|what we do|our work|portfolio|pricing",
        "detection_notes": "Searches for service-related keywords in navigation and page text.",
        "fallback_detection": "Manual review of website structure",
        "evidence_required": "Screenshots of 2-3 service pages showing detailed descriptions.",
        "evidence_type": "screenshot",
        "verification_method": "Browse website and confirm dedicated pages for each service offered.",
        "recommendation_action": "Create detailed service pages",
        "recommendation_detail": "Create a dedicated page for each service or product. Include description, benefits, pricing (where possible), and a CTA.",
        "effort": "medium",
        "estimated_time": "4-8 hours per page",
        "expected_impact": "+5 points (improves AI content understanding)",
        "prompt_reference": "service_pages",
        "ai_context_hint": "Detailed service pages help AI systems understand exactly what a business offers.",
        "methodology_reference": "Content optimisation guide (internal doc)",
        "version": "1.0",
        "sort_order": 9,
    },
    {
        "standard_id": "google_photos_v1",
        "name": "Google Business Photos",
        "slug": "photos",
        "category": "engagement",
        "subcategory": "visual",
        "importance": "medium",
        "weight": 4,
        "max_points": 5,
        "scoring_logic": "≥ 20 photos = 5 points, ≥ 10 = 3 points, ≥ 1 = 1 point, 0 = 0 points.",
        "detection_type": "api_call",
        "detection_pattern": "google_places_details.photos_count",
        "detection_notes": "Requires Google Places Details API.",
        "fallback_detection": "Manual count of photos on Google Business profile",
        "evidence_required": "Screenshot of Google Business profile showing photo gallery.",
        "evidence_type": "screenshot",
        "verification_method": "View Google Business profile and count photos in gallery.",
        "recommendation_action": "Add photos to Google Business profile",
        "recommendation_detail": "Upload at least 20 high-quality photos: exterior, interior, team, products/services, and team at work.",
        "effort": "low",
        "estimated_time": "1-2 hours",
        "expected_impact": "+5 points (improves profile completeness)",
        "prompt_reference": "google_business_improvements",
        "ai_context_hint": "Photo-rich profiles are weighted higher by AI recommendation systems.",
        "methodology_reference": "Google Business Profile optimisation guide",
        "version": "1.0",
        "sort_order": 10,
    },
    # ── Transparency ──
    {
        "standard_id": "about_page_v1",
        "name": "About Page",
        "slug": "about_page",
        "category": "transparency",
        "subcategory": "trust",
        "importance": "high",
        "weight": 6,
        "max_points": 5,
        "scoring_logic": "Check if website has an About page with company information. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"about us|about|our story|who we are|our team",
        "detection_notes": "Searches for about-related keywords in navigation and page text.",
        "fallback_detection": "Manual check of navigation menu",
        "evidence_required": "Screenshot of About page showing team, history, or mission.",
        "evidence_type": "screenshot",
        "verification_method": "Navigate to About page and verify it contains meaningful company information.",
        "recommendation_action": "Create a comprehensive About page",
        "recommendation_detail": "Tell your company story, introduce key team members, share your mission and values. Include photos of the team and workspace.",
        "effort": "low",
        "estimated_time": "2-4 hours",
        "expected_impact": "+5 points (builds trust through transparency)",
        "prompt_reference": "about_page",
        "ai_context_hint": "About pages help AI systems understand a business's legitimacy and expertise.",
        "methodology_reference": "Website trust signal guide (internal doc)",
        "version": "1.0",
        "sort_order": 11,
    },
    {
        "standard_id": "faq_v1",
        "name": "FAQ Section",
        "slug": "faq",
        "category": "transparency",
        "subcategory": "information",
        "importance": "medium",
        "weight": 4,
        "max_points": 5,
        "scoring_logic": "Check if website has an FAQ section. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"faq|frequently asked|common questions|help centre|knowledge base",
        "detection_notes": "Searches for FAQ-related keywords in page text and navigation.",
        "fallback_detection": "Manual review of website footer and navigation",
        "evidence_required": "Screenshot of FAQ page showing 5+ questions and answers.",
        "evidence_type": "screenshot",
        "verification_method": "Browse to FAQ page and verify it contains meaningful Q&A content.",
        "recommendation_action": "Add an FAQ section",
        "recommendation_detail": "Create an FAQ page with 10-15 common customer questions and detailed answers. Cover pricing, process, guarantees, and common concerns.",
        "effort": "low",
        "estimated_time": "2-3 hours",
        "expected_impact": "+5 points (answers AI and customer questions)",
        "prompt_reference": "faq",
        "ai_context_hint": "FAQ sections are frequently surfaced by AI in response to customer queries about a business.",
        "methodology_reference": "Content optimisation guide (internal doc)",
        "version": "1.0",
        "sort_order": 12,
    },
    {
        "standard_id": "privacy_policy_v1",
        "name": "Privacy Policy",
        "slug": "privacy_policy",
        "category": "transparency",
        "subcategory": "compliance",
        "importance": "high",
        "weight": 5,
        "max_points": 5,
        "scoring_logic": "Check if website has a privacy policy page. 5 points if found, 0 if not.",
        "detection_type": "regex",
        "detection_pattern": r"privacy policy|privacy|cookie policy|gdpr|data protection",
        "detection_notes": "Searches for privacy-related keywords in page text and footer links.",
        "fallback_detection": "Manual check of website footer",
        "evidence_required": "Screenshot of privacy policy page showing data handling information.",
        "evidence_type": "screenshot",
        "verification_method": "Scroll to footer and click Privacy Policy link. Verify content is comprehensive.",
        "recommendation_action": "Add a privacy policy page",
        "recommendation_detail": "Create a privacy policy covering data collection, storage, sharing, and user rights. Use a template and customise for your business.",
        "effort": "low",
        "estimated_time": "1-2 hours",
        "expected_impact": "+5 points (legal compliance + trust signal)",
        "prompt_reference": "improvement_recommendations",
        "ai_context_hint": "Privacy policies are increasingly weighted by AI as signals of business legitimacy.",
        "methodology_reference": "GDPR compliance checklist (internal doc)",
        "version": "1.0",
        "sort_order": 13,
    },
    # ── Technical ──
    {
        "standard_id": "mobile_responsive_v1",
        "name": "Mobile Responsive",
        "slug": "mobile_responsive",
        "category": "technical",
        "subcategory": "usability",
        "importance": "critical",
        "weight": 8,
        "max_points": 10,
        "scoring_logic": "Check if website has viewport meta tag and passes basic mobile responsiveness checks. 10 points if responsive, 0 if not.",
        "detection_type": "meta_tag",
        "detection_pattern": "viewport",
        "detection_notes": "Checks for <meta name='viewport'> tag in HTML head. Advanced check could use mobile emulation.",
        "fallback_detection": "Manual check using browser DevTools mobile viewport",
        "evidence_required": "Screenshot of website displayed on mobile device or browser mobile view.",
        "evidence_type": "screenshot",
        "verification_method": "Open website on a phone or use Chrome DevTools mobile viewport. Verify content is readable and navigable.",
        "recommendation_action": "Make website mobile-responsive",
        "recommendation_detail": "Implement responsive design using CSS media queries or a mobile-first framework. Test on multiple device sizes. Ensure buttons are tappable and text is readable without zooming.",
        "effort": "medium",
        "estimated_time": "4-16 hours depending on complexity",
        "expected_impact": "+10 points (critical for AI and mobile users)",
        "prompt_reference": "improvement_recommendations",
        "ai_context_hint": "Mobile responsiveness is a significant ranking factor for AI search results.",
        "methodology_reference": "Mobile optimisation guide (internal doc)",
        "version": "1.0",
        "sort_order": 14,
    },
]


async def seed_standard_library(db: AsyncSession):
    """Seed the trust standard library if empty."""
    result = await db.execute(select(func.count()).select_from(TrustStandardLibrary))
    count = result.scalar() or 0
    if count > 0:
        return

    for std_data in STANDARDS:
        std = TrustStandardLibrary(**std_data)
        db.add(std)

    await db.flush()
    print(f"Seeded {len(STANDARDS)} trust standards")